### ISSUE TITLE
Issues with certify.py

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw-geo-python#7]
There is some functionality in `certify.py` that I assume isn't currently being used because it appears to be broken.  On this line:
https://github.com/dengwirda/jigsaw-geo-python/blob/dev/jigsawpy/certify.py#L54
`nvals` is almost certainly unnecessary (and probably a remnant of C++ code or something).  The ndarray `vals` presumably contains its length.  Calls to this function do not include this argument:
https://github.com/dengwirda/jigsaw-geo-python/blob/dev/jigsawpy/certify.py#L132-L136

On this line:
https://github.com/dengwirda/jigsaw-geo-python/blob/dev/jigsawpy/certify.py#L62-L63
the variable `data` is not defined.  Presumably it should be `vals`?

I'm guessing this code just isn't getting called (yet) so these errors haven't come up yet.

**Comment by dengwirda** [comment]
All true -- will add new examples to call the different code paths.

**Comment by dengwirda** [comment]
This should hopefully all now be fixed in [jigsaw-python](https://github.com/dengwirda/jigsaw-python).
