### ISSUE TITLE
pathlib in setup.py

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw-geo-python#8]
Currently, `setup.py` uses pathlib.  
https://github.com/dengwirda/jigsaw-geo-python/blob/dev/setup.py#L5
This is not necessary, as my understanding is that `setup.py` should use unix-style paths even on Windows.  (All example `setup.py` files I have found, even those indicating Windows support, do this.)  It also causes a bit of trouble because it means that `pathlib` needs to be installed in the environment where `setup.py` is being called, which might be different from the environment where you actually want `jigsawpy` installed.  Typically, it is best to have a bare minimum of dependencies in `setup.py` itself. I strongly recommend just using unix-style paths and getting rid of thee `pathlib` import.

**Comment by dengwirda** [comment]
Yes, fair enough - I think I can replace it with `os.path.join`, etc and remove the `pathlib` dependency. I'll test on my windows machine and update.

**Comment by dengwirda** [comment]
I've fixed this for `setup.py` in [jigsaw-python](https://github.com/dengwirda/jigsaw-python).
